# Generated by Django 3.2.9 on 2022-03-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220318_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chatbotanswer',
            new_name='chatbotanswerm',
        ),
        migrations.RenameModel(
            old_name='studentsms',
            new_name='studentsmsm',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='altcontact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='altemailid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='caddressline1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='caddressline2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ccityid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ccityid', to='home.citym'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clandmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='paddressline1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='paddressline2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pcityid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcityid', to='home.citym'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plandmark',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ppincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Faculty'), ('3', 'Student')], default=3, max_length=50),
        ),
    ]
