# Generated by Django 3.2.9 on 2022-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_coursem_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='programcode',
            field=models.CharField(max_length=20),
        ),
    ]
