# Generated by Django 3.2.9 on 2022-03-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_programm_programcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursem',
            old_name='prrogramid',
            new_name='programid',
        ),
        migrations.AddField(
            model_name='coursem',
            name='semesterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.semesterm'),
            preserve_default=False,
        ),
    ]
