# Generated by Django 3.2.9 on 2022-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220319_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other')], max_length=50),
        ),
    ]
