# Generated by Django 3.2.9 on 2022-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_customuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsmsm',
            name='smssubject',
            field=models.CharField(default='', max_length=250),
        ),
    ]
