# Generated by Django 3.2.9 on 2022-03-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_adminsmsm_smssubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsmsm',
            name='smsdate',
            field=models.DateField(null=True),
        ),
    ]
