# Generated by Django 3.2.9 on 2022-03-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignmentt',
            name='submissiondate',
            field=models.DateField(auto_now=True),
        ),
    ]
