# Generated by Django 3.2.9 on 2022-03-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_studentassignmentt_submissiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcomponentm',
            name='studentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studentm'),
        ),
    ]
