# Generated by Django 3.2.9 on 2022-03-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_crmcomponentm_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcomponentm',
            name='chatbot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmcomponentm',
            name='directinquiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmcomponentm',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmcomponentm',
            name='studentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studentm'),
        ),
        migrations.AlterField(
            model_name='crmcomponentm',
            name='voice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
