# Generated by Django 3.2.9 on 2022-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20220327_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotanswerm',
            name='isrelevent',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotquestionm',
            name='chatbotquestiontype',
            field=models.CharField(max_length=20),
        ),
    ]
