# Generated by Django 3.2.9 on 2022-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220327_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmsm',
            name='smsanswer',
        ),
        migrations.AlterField(
            model_name='chatbotanswerm',
            name='chatbotanswer',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='studentsmsm',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='voicem',
            name='remark',
            field=models.CharField(max_length=250),
        ),
    ]
