# Generated by Django 3.2.9 on 2022-03-30 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220330_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmcomponentm',
            name='studentid',
        ),
        migrations.AddField(
            model_name='crmcomponentm',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
